import Head from "next/head";
import ProjectsCard from "../components/ProjectsCard";

export default function Home() {
	return (
		<div>
			<Head>
				<title>My Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<ProjectsCard />
			</main>
		</div>
	);
}
